# Generated by Django 5.2.5 on 2025-09-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade_id', models.IntegerField()),
                ('student_id', models.CharField(max_length=100)),
                ('sub_id', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('remark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_units', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('sub_code', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
