# Generated by Django 5.2.5 on 2025-09-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_course_grades_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='subjects',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
