# Generated by Django 5.2.5 on 2025-09-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_attendance_notification_alter_subjects_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='sub_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
