# Generated by Django 5.2.5 on 2025-09-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0004_alter_subjects_sub_code_alter_subjects_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='course_subject',
        ),
    ]
