# Generated by Django 5.2.5 on 2025-09-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0005_rename_course_name_course_course_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grades',
            old_name='student_id',
            new_name='student_name',
        ),
    ]
