# Generated by Django 5.2.5 on 2025-09-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0006_rename_student_id_grades_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grades',
            old_name='sub_id',
            new_name='course_taken',
        ),
    ]
