# Generated by Django 5.2.5 on 2025-09-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0007_rename_sub_id_grades_course_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='remark',
            field=models.CharField(max_length=100),
        ),
    ]
